/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\Code\\Blog\\vuepress.blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1323e1d4",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1323e1d4").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-97ebf5d8",
    path: "/guide/Algorithm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97ebf5d8").then(next)
    },
  },
  {
    path: "/guide/Algorithm/index.html",
    redirect: "/guide/Algorithm/"
  },
  {
    name: "v-6d8eff35",
    path: "/guide/Algorithm/389.diff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d8eff35").then(next)
    },
  },
  {
    name: "v-4accb072",
    path: "/guide/BLOG/BetterScroll.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4accb072").then(next)
    },
  },
  {
    name: "v-192848c7",
    path: "/guide/BLOG/AutoSideBar2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-192848c7").then(next)
    },
  },
  {
    name: "v-62fbdf2d",
    path: "/guide/BLOG/AutoSideBar.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62fbdf2d").then(next)
    },
  },
  {
    name: "v-bce7f0f8",
    path: "/guide/BLOG/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bce7f0f8").then(next)
    },
  },
  {
    path: "/guide/BLOG/index.html",
    redirect: "/guide/BLOG/"
  },
  {
    name: "v-e79d04b2",
    path: "/guide/BLOG/Single.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e79d04b2").then(next)
    },
  },
  {
    name: "v-09c2586f",
    path: "/config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09c2586f").then(next)
    },
  },
  {
    name: "v-467d433a",
    path: "/guide/BLOG/TailRecursion.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-467d433a").then(next)
    },
  },
  {
    name: "v-314dec32",
    path: "/guide/BLOG/about;.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-314dec32").then(next)
    },
  },
  {
    name: "v-12a2884f",
    path: "/guide/BLOG/Watcher.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12a2884f").then(next)
    },
  },
  {
    name: "v-3e54e3c7",
    path: "/guide/BLOG/copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e54e3c7").then(next)
    },
  },
  {
    name: "v-4f9e3607",
    path: "/guide/BLOG/autosidebar4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f9e3607").then(next)
    },
  },
  {
    name: "v-5fdcbd32",
    path: "/guide/BLOG/autosidebar3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fdcbd32").then(next)
    },
  },
  {
    name: "v-335739c7",
    path: "/guide/BLOG/debounce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-335739c7").then(next)
    },
  },
  {
    name: "v-06267711",
    path: "/guide/BLOG/closure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06267711").then(next)
    },
  },
  {
    name: "v-6c8498c1",
    path: "/guide/BLOG/gitpageConfig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c8498c1").then(next)
    },
  },
  {
    name: "v-64474ee7",
    path: "/guide/BLOG/newVue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64474ee7").then(next)
    },
  },
  {
    name: "v-312d5627",
    path: "/guide/BLOG/nginxconf2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-312d5627").then(next)
    },
  },
  {
    name: "v-761d2727",
    path: "/guide/BLOG/presentational-container-pattern.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-761d2727").then(next)
    },
  },
  {
    name: "v-c1c898f2",
    path: "/guide/BLOG/mianshizongjie.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c1c898f2").then(next)
    },
  },
  {
    name: "v-75b41951",
    path: "/guide/BLOG/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75b41951").then(next)
    },
  },
  {
    name: "v-55f6994a",
    path: "/guide/BLOG/vuenexttick.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55f6994a").then(next)
    },
  },
  {
    name: "v-34e82ae7",
    path: "/guide/BLOG/vueBlog2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34e82ae7").then(next)
    },
  },
  {
    name: "v-ea1cb5b2",
    path: "/guide/BLOG/vueBlog4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea1cb5b2").then(next)
    },
  },
  {
    name: "v-2951b587",
    path: "/guide/BLOG/watchMovie.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2951b587").then(next)
    },
  },
  {
    name: "v-c36185ae",
    path: "/guide/BLOG/watch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c36185ae").then(next)
    },
  },
  {
    name: "v-1890d132",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1890d132").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-a430e1cc",
    path: "/guide/contact.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a430e1cc").then(next)
    },
  },
  {
    name: "v-2b1eb587",
    path: "/guide/BLOG/promise2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b1eb587").then(next)
    },
  },
  {
    name: "v-7cd147fa",
    path: "/guide/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7cd147fa").then(next)
    },
  },
  {
    name: "v-1b791ae2",
    path: "/guide/daily/2020.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b791ae2").then(next)
    },
  },
  {
    name: "v-7703af80",
    path: "/guide/daily/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7703af80").then(next)
    },
  },
  {
    path: "/guide/daily/index.html",
    redirect: "/guide/daily/"
  },
  {
    name: "v-5fece807",
    path: "/guide/BLOG/vueBlog3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fece807").then(next)
    },
  },
  {
    name: "v-98864f6e",
    path: "/guide/daily/2monthWork.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-98864f6e").then(next)
    },
  },
  {
    name: "v-294465ed",
    path: "/guide/daily/Today.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-294465ed").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]