/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DOUMJUN",
  "description": "欢迎访问我的博客",
  "base": "/vuepress.blog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "DOUMJUN",
        "actionText": "WELCOME →",
        "actionLink": "/guide/",
        "features": null
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-157c0639",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-b67c1a2c",
      "path": "/config.html"
    },
    {
      "title": "Better-Scroll的使用",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/BetterScroll.html",
      "relativePath": "guide/BLOG/BetterScroll.md",
      "key": "v-795238fc",
      "path": "/guide/BLOG/BetterScroll.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "注意",
          "slug": "注意"
        }
      ]
    },
    {
      "title": "学习记录",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/",
      "relativePath": "guide/BLOG/README.md",
      "key": "v-1102a229",
      "path": "/guide/BLOG/"
    },
    {
      "title": "自动修改侧边栏的工具AutoSideBar()",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/guide/BLOG/AutoSideBar.html",
      "relativePath": "guide/BLOG/AutoSideBar.md",
      "key": "v-7fbacda8",
      "path": "/guide/BLOG/AutoSideBar.html",
      "headers": [
        {
          "level": 2,
          "title": "想法",
          "slug": "想法"
        },
        {
          "level": 2,
          "title": "思路",
          "slug": "思路"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "踩到的坑和笔记",
          "slug": "踩到的坑和笔记"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "我的博客",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-8ea96768",
      "path": "/guide/",
      "headers": [
        {
          "level": 3,
          "title": "记录",
          "slug": "记录"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/guide/about.html",
      "relativePath": "guide/about.md",
      "key": "v-7b0b7696",
      "path": "/guide/about.html"
    },
    {
      "title": "联系我",
      "frontmatter": {},
      "regularPath": "/guide/contact.html",
      "relativePath": "guide/contact.md",
      "key": "v-6e049356",
      "path": "/guide/contact.html"
    },
    {
      "title": "daily readme",
      "frontmatter": {},
      "regularPath": "/guide/daily/",
      "relativePath": "guide/daily/README.md",
      "key": "v-39839636",
      "path": "/guide/daily/"
    },
    {
      "title": "Today",
      "frontmatter": {},
      "regularPath": "/guide/daily/Today.html",
      "relativePath": "guide/daily/Today.md",
      "key": "v-67092228",
      "path": "/guide/daily/Today.html"
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/guide/about",
        "target": ""
      },
      {
        "text": "博客",
        "link": "/guide/BLOG/",
        "target": ""
      },
      {
        "text": "日常",
        "link": "/guide/daily/",
        "target": ""
      },
      {
        "text": "更多",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/DouMJun",
            "target": "_blank"
          },
          {
            "text": "bilibili",
            "link": "https://space.bilibili.com/8096424",
            "target": "_blank"
          }
        ]
      }
    ],
    "sidebar": {
      "/guide/BLOG/": [
        {
          "title": "博客",
          "children": [
            "AutoSideBar",
            "BetterScroll"
          ]
        }
      ],
      "/guide/daily/": [
        {
          "title": "日常",
          "children": [
            "Today"
          ]
        }
      ],
      "/guide/": [
        {
          "title": "首页",
          "children": [
            "contact"
          ]
        }
      ]
    },
    "lastUpdated": "Last Updated",
    "smoothScroll": true
  }
}