/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DOUMJUN",
  "description": "欢迎访问我的博客",
  "base": "/vuepress.blog/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "DOUMJUN",
        "actionText": "WELCOME →",
        "actionLink": "/guide/about",
        "features": [
          {
            "title": "博客",
            "details": "记录学习中的困惑和问题，把想法写下来"
          },
          {
            "title": "日常",
            "details": "记录生活的点点滴滴"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-157c0639",
      "path": "/",
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "找不同",
      "frontmatter": {},
      "regularPath": "/guide/Algorithm/389.diff.html",
      "relativePath": "guide/Algorithm/389.diff.md",
      "key": "v-1bec3830",
      "path": "/guide/Algorithm/389.diff.html",
      "headers": [
        {
          "level": 2,
          "title": "题目",
          "slug": "题目"
        },
        {
          "level": 2,
          "title": "解法",
          "slug": "解法"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2020, 9:41:47 PM"
    },
    {
      "title": "数据结构与算法",
      "frontmatter": {},
      "regularPath": "/guide/Algorithm/",
      "relativePath": "guide/Algorithm/README.md",
      "key": "v-52ef5579",
      "path": "/guide/Algorithm/",
      "lastUpdated": "12/18/2020, 9:41:47 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-b67c1a2c",
      "path": "/config.html",
      "lastUpdated": "11/5/2020, 10:39:34 PM"
    },
    {
      "title": "AutoSideBar2",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/AutoSideBar2.html",
      "relativePath": "guide/BLOG/AutoSideBar2.md",
      "key": "v-01e58482",
      "path": "/guide/BLOG/AutoSideBar2.html",
      "headers": [
        {
          "level": 3,
          "title": "起因",
          "slug": "起因"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "自动修改侧边栏的工具AutoSideBar()",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/guide/BLOG/AutoSideBar.html",
      "relativePath": "guide/BLOG/AutoSideBar.md",
      "key": "v-7fbacda8",
      "path": "/guide/BLOG/AutoSideBar.html",
      "headers": [
        {
          "level": 2,
          "title": "想法",
          "slug": "想法"
        },
        {
          "level": 2,
          "title": "思路",
          "slug": "思路"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "踩到的坑和笔记",
          "slug": "踩到的坑和笔记"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/5/2020, 10:39:34 PM"
    },
    {
      "title": "Better-Scroll的使用",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/BetterScroll.html",
      "relativePath": "guide/BLOG/BetterScroll.md",
      "key": "v-795238fc",
      "path": "/guide/BLOG/BetterScroll.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "注意",
          "slug": "注意"
        }
      ],
      "lastUpdated": "11/5/2020, 10:39:34 PM"
    },
    {
      "title": "学习记录",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/",
      "relativePath": "guide/BLOG/README.md",
      "key": "v-1102a229",
      "path": "/guide/BLOG/",
      "headers": [
        {
          "level": 3,
          "title": "学习记录",
          "slug": "学习记录"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "JS单例模式",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/Single.html",
      "relativePath": "guide/BLOG/Single.md",
      "key": "v-6c138c3c",
      "path": "/guide/BLOG/Single.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是单例",
          "slug": "什么是单例"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/16/2020, 10:45:12 PM"
    },
    {
      "title": "尾调用优化",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/TailRecursion.html",
      "relativePath": "guide/BLOG/TailRecursion.md",
      "key": "v-e9c2d144",
      "path": "/guide/BLOG/TailRecursion.html",
      "headers": [
        {
          "level": 2,
          "title": "原理",
          "slug": "原理"
        },
        {
          "level": 3,
          "title": "尾调用",
          "slug": "尾调用"
        },
        {
          "level": 3,
          "title": "尾递归",
          "slug": "尾递归"
        },
        {
          "level": 2,
          "title": "尾递归优化实现",
          "slug": "尾递归优化实现"
        },
        {
          "level": 3,
          "title": "蹦床函数(trampoline)",
          "slug": "蹦床函数-trampoline"
        },
        {
          "level": 3,
          "title": "尾递归优化",
          "slug": "尾递归优化"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "AutoSideBar3",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/autosidebar3.html",
      "relativePath": "guide/BLOG/autosidebar3.md",
      "key": "v-8e6245bc",
      "path": "/guide/BLOG/autosidebar3.html",
      "headers": [
        {
          "level": 2,
          "title": "改进",
          "slug": "改进"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "自动侧边栏插件",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/autosidebar4.html",
      "relativePath": "guide/BLOG/autosidebar4.md",
      "key": "v-385b71c2",
      "path": "/guide/BLOG/autosidebar4.html",
      "headers": [
        {
          "level": 2,
          "title": "如何使用：",
          "slug": "如何使用"
        },
        {
          "level": 2,
          "title": "上传npm插件",
          "slug": "上传npm插件"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/26/2020, 10:39:49 PM"
    },
    {
      "title": "深浅拷贝",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/copy.html",
      "relativePath": "guide/BLOG/copy.md",
      "key": "v-073ef582",
      "path": "/guide/BLOG/copy.html",
      "headers": [
        {
          "level": 2,
          "title": "浅拷贝",
          "slug": "浅拷贝"
        },
        {
          "level": 2,
          "title": "深拷贝",
          "slug": "深拷贝"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/11/2020, 9:48:03 PM"
    },
    {
      "title": "关于闭包",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/closure.html",
      "relativePath": "guide/BLOG/closure.md",
      "key": "v-34a5dee8",
      "path": "/guide/BLOG/closure.html",
      "headers": [
        {
          "level": 2,
          "title": "定义",
          "slug": "定义"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 2,
          "title": "一个巧妙的用法",
          "slug": "一个巧妙的用法"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "关于最近面试的总结",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/mianshizongjie.html",
      "relativePath": "guide/BLOG/mianshizongjie.md",
      "key": "v-2b0e99c2",
      "path": "/guide/BLOG/mianshizongjie.html",
      "headers": [
        {
          "level": 2,
          "title": "一些收获",
          "slug": "一些收获"
        },
        {
          "level": 2,
          "title": "槽点",
          "slug": "槽点"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "关于防抖与节流",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/debounce.html",
      "relativePath": "guide/BLOG/debounce.md",
      "key": "v-4b9d6082",
      "path": "/guide/BLOG/debounce.html",
      "headers": [
        {
          "level": 2,
          "title": "简单实现",
          "slug": "简单实现"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "用Nginx在同一端口挂多个页面",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/nginxconf2.html",
      "relativePath": "guide/BLOG/nginxconf2.md",
      "key": "v-4f88b13c",
      "path": "/guide/BLOG/nginxconf2.html",
      "headers": [
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/26/2020, 10:39:49 PM"
    },
    {
      "title": "写一个Promise(二)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/promise2.html",
      "relativePath": "guide/BLOG/promise2.md",
      "key": "v-4364dc42",
      "path": "/guide/BLOG/promise2.html",
      "headers": [
        {
          "level": 2,
          "title": "Promise.all",
          "slug": "promise-all"
        },
        {
          "level": 2,
          "title": "Promise.race",
          "slug": "promise-race"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/16/2020, 10:45:12 PM"
    },
    {
      "title": "写一个Promise(一)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/promise.html",
      "relativePath": "guide/BLOG/promise.md",
      "key": "v-553ab2cc",
      "path": "/guide/BLOG/promise.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/12/2020, 11:36:37 AM"
    },
    {
      "title": "从零开始的博客开发(2)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vueBlog2.html",
      "relativePath": "guide/BLOG/vueBlog2.md",
      "key": "v-4d2e51a2",
      "path": "/guide/BLOG/vueBlog2.html",
      "headers": [
        {
          "level": 2,
          "title": "功能与问题",
          "slug": "功能与问题"
        },
        {
          "level": 2,
          "title": "解决",
          "slug": "解决"
        }
      ],
      "lastUpdated": "11/25/2020, 10:38:53 PM"
    },
    {
      "title": "从零开始的博客开发(3.1)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vueBlog4.html",
      "relativePath": "guide/BLOG/vueBlog4.md",
      "key": "v-b990683c",
      "path": "/guide/BLOG/vueBlog4.html",
      "headers": [
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/25/2020, 10:38:53 PM"
    },
    {
      "title": "关于Vue.nextTick",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vuenexttick.html",
      "relativePath": "guide/BLOG/vuenexttick.md",
      "key": "v-1c78bc54",
      "path": "/guide/BLOG/vuenexttick.html",
      "headers": [
        {
          "level": 2,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 2,
          "title": "异步更新队列",
          "slug": "异步更新队列"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "从零开始的博客开发(3)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vueBlog3.html",
      "relativePath": "guide/BLOG/vueBlog3.md",
      "key": "v-78330ec2",
      "path": "/guide/BLOG/vueBlog3.html",
      "headers": [
        {
          "level": 2,
          "title": "功能与问题",
          "slug": "功能与问题"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 3,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 3,
          "title": "返回顶部",
          "slug": "返回顶部"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/25/2020, 10:38:53 PM"
    },
    {
      "title": "如何用CSS做一个时钟",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/watch.html",
      "relativePath": "guide/BLOG/watch.md",
      "key": "v-560867b8",
      "path": "/guide/BLOG/watch.html",
      "lastUpdated": "12/11/2020, 9:48:03 PM"
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/guide/about.html",
      "relativePath": "guide/about.md",
      "key": "v-7b0b7696",
      "path": "/guide/about.html",
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "我的博客",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-8ea96768",
      "path": "/guide/",
      "headers": [
        {
          "level": 3,
          "title": "记录",
          "slug": "记录"
        }
      ],
      "lastUpdated": "11/5/2020, 10:39:34 PM"
    },
    {
      "title": "联系我",
      "frontmatter": {},
      "regularPath": "/guide/contact.html",
      "relativePath": "guide/contact.md",
      "key": "v-6e049356",
      "path": "/guide/contact.html",
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "生活日常",
      "frontmatter": {},
      "regularPath": "/guide/daily/",
      "relativePath": "guide/daily/README.md",
      "key": "v-39839636",
      "path": "/guide/daily/",
      "lastUpdated": "11/23/2020, 10:42:28 PM"
    },
    {
      "title": "Today",
      "frontmatter": {},
      "regularPath": "/guide/daily/Today.html",
      "relativePath": "guide/daily/Today.md",
      "key": "v-67092228",
      "path": "/guide/daily/Today.html",
      "lastUpdated": "11/5/2020, 10:39:34 PM"
    },
    {
      "title": "关于setImmediate()的执行",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/Watcher.html",
      "relativePath": "guide/BLOG/Watcher.md",
      "key": "v-1badbc6c",
      "path": "/guide/BLOG/Watcher.html",
      "headers": [
        {
          "level": 2,
          "title": "关于setImmediate()",
          "slug": "关于setimmediate"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/17/2020, 11:00:01 PM"
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/guide/about",
        "target": ""
      },
      {
        "text": "博客",
        "link": "/guide/BLOG/",
        "target": ""
      },
      {
        "text": "算法",
        "link": "/guide/Algorithm/",
        "target": ""
      },
      {
        "text": "日常",
        "link": "/guide/daily/",
        "target": ""
      },
      {
        "text": "更多",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/DouMJun",
            "target": "_blank"
          },
          {
            "text": "bilibili",
            "link": "https://space.bilibili.com/8096424",
            "target": "_blank"
          }
        ]
      }
    ],
    "sidebar": {
      "/guide/BLOG/": [
        {
          "title": "博客",
          "children": [
            "vuenexttick",
            "Watcher",
            "Single",
            "promise2",
            "watch",
            "copy",
            "autosidebar4",
            "nginxconf2",
            "vueBlog4",
            "promise",
            "vueBlog3",
            "debounce",
            "vueBlog2",
            "autosidebar3",
            "mianshizongjie",
            "TailRecursion",
            "closure",
            "AutoSideBar2",
            "BetterScroll",
            "AutoSideBar"
          ]
        }
      ],
      "/guide/daily/": [
        {
          "title": "日常",
          "children": [
            "Today"
          ]
        }
      ],
      "/guide/Algorithm/": [
        {
          "title": "算法",
          "children": [
            "389.diff"
          ]
        }
      ],
      "/guide/": [
        {
          "title": "首页",
          "children": [
            "contact"
          ]
        }
      ]
    },
    "lastUpdated": "Last Updated"
  }
}