/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "DOUMJUN",
  "description": "欢迎访问我的博客",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "DOUMJUN",
        "actionText": "WELCOME →",
        "actionLink": "/guide/about",
        "features": [
          {
            "title": "博客",
            "details": "记录学习中的困惑和问题，把想法写下来"
          },
          {
            "title": "日常",
            "details": "记录生活的点点滴滴"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1323e1d4",
      "path": "/",
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "数据结构与算法",
      "frontmatter": {},
      "regularPath": "/guide/Algorithm/",
      "relativePath": "guide/Algorithm/README.md",
      "key": "v-97ebf5d8",
      "path": "/guide/Algorithm/",
      "lastUpdated": "12/18/2020, 9:41:47 PM",
      "lastUpdatedTimestamp": 1608298907000
    },
    {
      "title": "找不同",
      "frontmatter": {},
      "regularPath": "/guide/Algorithm/389.diff.html",
      "relativePath": "guide/Algorithm/389.diff.md",
      "key": "v-6d8eff35",
      "path": "/guide/Algorithm/389.diff.html",
      "headers": [
        {
          "level": 2,
          "title": "题目",
          "slug": "题目"
        },
        {
          "level": 2,
          "title": "解法",
          "slug": "解法"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/18/2020, 9:41:47 PM",
      "lastUpdatedTimestamp": 1608298907000
    },
    {
      "title": "Better-Scroll的使用",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/BetterScroll.html",
      "relativePath": "guide/BLOG/BetterScroll.md",
      "key": "v-4accb072",
      "path": "/guide/BLOG/BetterScroll.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "注意",
          "slug": "注意"
        }
      ],
      "lastUpdated": "11/5/2020, 10:39:34 PM",
      "lastUpdatedTimestamp": 1604587174000
    },
    {
      "title": "AutoSideBar2",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/AutoSideBar2.html",
      "relativePath": "guide/BLOG/AutoSideBar2.md",
      "key": "v-192848c7",
      "path": "/guide/BLOG/AutoSideBar2.html",
      "headers": [
        {
          "level": 3,
          "title": "起因",
          "slug": "起因"
        },
        {
          "level": 3,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 3,
          "title": "使用",
          "slug": "使用"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "自动修改侧边栏的工具AutoSideBar()",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/guide/BLOG/AutoSideBar.html",
      "relativePath": "guide/BLOG/AutoSideBar.md",
      "key": "v-62fbdf2d",
      "path": "/guide/BLOG/AutoSideBar.html",
      "headers": [
        {
          "level": 2,
          "title": "想法",
          "slug": "想法"
        },
        {
          "level": 2,
          "title": "思路",
          "slug": "思路"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "踩到的坑和笔记",
          "slug": "踩到的坑和笔记"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/5/2020, 10:39:34 PM",
      "lastUpdatedTimestamp": 1604587174000
    },
    {
      "title": "学习记录",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/",
      "relativePath": "guide/BLOG/README.md",
      "key": "v-bce7f0f8",
      "path": "/guide/BLOG/",
      "headers": [
        {
          "level": 3,
          "title": "学习记录",
          "slug": "学习记录"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "JS单例模式",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/Single.html",
      "relativePath": "guide/BLOG/Single.md",
      "key": "v-e79d04b2",
      "path": "/guide/BLOG/Single.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是单例",
          "slug": "什么是单例"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/16/2020, 10:45:12 PM",
      "lastUpdatedTimestamp": 1608129912000
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-09c2586f",
      "path": "/config.html",
      "lastUpdated": "11/5/2020, 10:39:34 PM",
      "lastUpdatedTimestamp": 1604587174000
    },
    {
      "title": "尾调用优化",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/TailRecursion.html",
      "relativePath": "guide/BLOG/TailRecursion.md",
      "key": "v-467d433a",
      "path": "/guide/BLOG/TailRecursion.html",
      "headers": [
        {
          "level": 2,
          "title": "原理",
          "slug": "原理"
        },
        {
          "level": 3,
          "title": "尾调用",
          "slug": "尾调用"
        },
        {
          "level": 3,
          "title": "尾递归",
          "slug": "尾递归"
        },
        {
          "level": 2,
          "title": "尾递归优化实现",
          "slug": "尾递归优化实现"
        },
        {
          "level": 3,
          "title": "蹦床函数(trampoline)",
          "slug": "蹦床函数-trampoline"
        },
        {
          "level": 3,
          "title": "尾递归优化",
          "slug": "尾递归优化"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "关于分号“;”",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/about;.html",
      "relativePath": "guide/BLOG/about;.md",
      "key": "v-314dec32",
      "path": "/guide/BLOG/about;.html",
      "headers": [
        {
          "level": 2,
          "title": "起因",
          "slug": "起因"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "7/6/2021, 10:28:05 PM",
      "lastUpdatedTimestamp": 1625581685000
    },
    {
      "title": "关于setImmediate()的执行",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/Watcher.html",
      "relativePath": "guide/BLOG/Watcher.md",
      "key": "v-12a2884f",
      "path": "/guide/BLOG/Watcher.html",
      "headers": [
        {
          "level": 2,
          "title": "关于setImmediate()",
          "slug": "关于setimmediate"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/23/2020, 10:21:04 PM",
      "lastUpdatedTimestamp": 1608733264000
    },
    {
      "title": "深浅拷贝",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/copy.html",
      "relativePath": "guide/BLOG/copy.md",
      "key": "v-3e54e3c7",
      "path": "/guide/BLOG/copy.html",
      "headers": [
        {
          "level": 2,
          "title": "浅拷贝",
          "slug": "浅拷贝"
        },
        {
          "level": 2,
          "title": "深拷贝",
          "slug": "深拷贝"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/11/2020, 9:48:03 PM",
      "lastUpdatedTimestamp": 1607694483000
    },
    {
      "title": "自动侧边栏插件",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/autosidebar4.html",
      "relativePath": "guide/BLOG/autosidebar4.md",
      "key": "v-4f9e3607",
      "path": "/guide/BLOG/autosidebar4.html",
      "headers": [
        {
          "level": 2,
          "title": "如何使用：",
          "slug": "如何使用"
        },
        {
          "level": 2,
          "title": "上传npm插件",
          "slug": "上传npm插件"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/26/2020, 10:39:49 PM",
      "lastUpdatedTimestamp": 1606401589000
    },
    {
      "title": "AutoSideBar3",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/autosidebar3.html",
      "relativePath": "guide/BLOG/autosidebar3.md",
      "key": "v-5fdcbd32",
      "path": "/guide/BLOG/autosidebar3.html",
      "headers": [
        {
          "level": 2,
          "title": "改进",
          "slug": "改进"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "关于防抖与节流",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/debounce.html",
      "relativePath": "guide/BLOG/debounce.md",
      "key": "v-335739c7",
      "path": "/guide/BLOG/debounce.html",
      "headers": [
        {
          "level": 2,
          "title": "简单实现",
          "slug": "简单实现"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "关于闭包",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/closure.html",
      "relativePath": "guide/BLOG/closure.md",
      "key": "v-06267711",
      "path": "/guide/BLOG/closure.html",
      "headers": [
        {
          "level": 2,
          "title": "定义",
          "slug": "定义"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        },
        {
          "level": 2,
          "title": "一个巧妙的用法",
          "slug": "一个巧妙的用法"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "vuepress自定义域名配置",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/gitpageConfig.html",
      "relativePath": "guide/BLOG/gitpageConfig.md",
      "key": "v-6c8498c1",
      "path": "/guide/BLOG/gitpageConfig.html",
      "lastUpdated": "9/1/2022, 3:21:06 PM",
      "lastUpdatedTimestamp": 1662016866000
    },
    {
      "title": "Vue的初始化",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/newVue.html",
      "relativePath": "guide/BLOG/newVue.md",
      "key": "v-64474ee7",
      "path": "/guide/BLOG/newVue.html",
      "headers": [
        {
          "level": 2,
          "title": "初始化流程",
          "slug": "初始化流程"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/24/2020, 10:04:36 PM",
      "lastUpdatedTimestamp": 1608818676000
    },
    {
      "title": "用Nginx在同一端口挂多个页面",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/nginxconf2.html",
      "relativePath": "guide/BLOG/nginxconf2.md",
      "key": "v-312d5627",
      "path": "/guide/BLOG/nginxconf2.html",
      "headers": [
        {
          "level": 2,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/26/2020, 10:39:49 PM",
      "lastUpdatedTimestamp": 1606401589000
    },
    {
      "title": "容器/展示器模式",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/presentational-container-pattern.html",
      "relativePath": "guide/BLOG/presentational-container-pattern.md",
      "key": "v-761d2727",
      "path": "/guide/BLOG/presentational-container-pattern.html",
      "headers": [
        {
          "level": 2,
          "title": "展示组件",
          "slug": "展示组件"
        },
        {
          "level": 2,
          "title": "容器组件",
          "slug": "容器组件"
        },
        {
          "level": 2,
          "title": "Hooks",
          "slug": "hooks"
        },
        {
          "level": 2,
          "title": "优缺点",
          "slug": "优缺点"
        },
        {
          "level": 2,
          "title": "Reference",
          "slug": "reference"
        },
        {
          "level": 2,
          "title": "一点点吐槽",
          "slug": "一点点吐槽"
        }
      ],
      "lastUpdated": "8/25/2022, 4:17:29 PM",
      "lastUpdatedTimestamp": 1661415449000
    },
    {
      "title": "关于最近面试的总结",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/mianshizongjie.html",
      "relativePath": "guide/BLOG/mianshizongjie.md",
      "key": "v-c1c898f2",
      "path": "/guide/BLOG/mianshizongjie.html",
      "headers": [
        {
          "level": 2,
          "title": "一些收获",
          "slug": "一些收获"
        },
        {
          "level": 2,
          "title": "槽点",
          "slug": "槽点"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "写一个Promise(一)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/promise.html",
      "relativePath": "guide/BLOG/promise.md",
      "key": "v-75b41951",
      "path": "/guide/BLOG/promise.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/12/2020, 11:36:37 AM",
      "lastUpdatedTimestamp": 1607744197000
    },
    {
      "title": "关于Vue.nextTick",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vuenexttick.html",
      "relativePath": "guide/BLOG/vuenexttick.md",
      "key": "v-55f6994a",
      "path": "/guide/BLOG/vuenexttick.html",
      "headers": [
        {
          "level": 2,
          "title": "用法",
          "slug": "用法"
        },
        {
          "level": 2,
          "title": "异步更新队列",
          "slug": "异步更新队列"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "12/23/2020, 10:21:04 PM",
      "lastUpdatedTimestamp": 1608733264000
    },
    {
      "title": "从零开始的博客开发(2)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vueBlog2.html",
      "relativePath": "guide/BLOG/vueBlog2.md",
      "key": "v-34e82ae7",
      "path": "/guide/BLOG/vueBlog2.html",
      "headers": [
        {
          "level": 2,
          "title": "功能与问题",
          "slug": "功能与问题"
        },
        {
          "level": 2,
          "title": "解决",
          "slug": "解决"
        }
      ],
      "lastUpdated": "7/5/2021, 5:16:12 PM",
      "lastUpdatedTimestamp": 1625476572000
    },
    {
      "title": "从零开始的博客开发(3.1)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vueBlog4.html",
      "relativePath": "guide/BLOG/vueBlog4.md",
      "key": "v-ea1cb5b2",
      "path": "/guide/BLOG/vueBlog4.html",
      "headers": [
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/25/2020, 10:38:53 PM",
      "lastUpdatedTimestamp": 1606315133000
    },
    {
      "title": "一起看电影吧！",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/watchMovie.html",
      "relativePath": "guide/BLOG/watchMovie.md",
      "key": "v-2951b587",
      "path": "/guide/BLOG/watchMovie.html",
      "headers": [
        {
          "level": 2,
          "title": "实现思路",
          "slug": "实现思路"
        },
        {
          "level": 2,
          "title": "代码",
          "slug": "代码"
        },
        {
          "level": 2,
          "title": "问题",
          "slug": "问题"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "1/7/2021, 7:45:34 PM",
      "lastUpdatedTimestamp": 1610019934000
    },
    {
      "title": "如何用CSS做一个时钟",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/watch.html",
      "relativePath": "guide/BLOG/watch.md",
      "key": "v-c36185ae",
      "path": "/guide/BLOG/watch.html",
      "lastUpdated": "12/11/2020, 9:48:03 PM",
      "lastUpdatedTimestamp": 1607694483000
    },
    {
      "title": "我的博客",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-1890d132",
      "path": "/guide/",
      "headers": [
        {
          "level": 3,
          "title": "记录",
          "slug": "记录"
        }
      ],
      "lastUpdated": "11/5/2020, 10:39:34 PM",
      "lastUpdatedTimestamp": 1604587174000
    },
    {
      "title": "联系我",
      "frontmatter": {},
      "regularPath": "/guide/contact.html",
      "relativePath": "guide/contact.md",
      "key": "v-a430e1cc",
      "path": "/guide/contact.html",
      "lastUpdated": "8/29/2022, 6:31:59 PM",
      "lastUpdatedTimestamp": 1661769119000
    },
    {
      "title": "写一个Promise(二)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/promise2.html",
      "relativePath": "guide/BLOG/promise2.md",
      "key": "v-2b1eb587",
      "path": "/guide/BLOG/promise2.html",
      "headers": [
        {
          "level": 2,
          "title": "Promise.all",
          "slug": "promise-all"
        },
        {
          "level": 2,
          "title": "Promise.race",
          "slug": "promise-race"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "7/5/2021, 5:16:12 PM",
      "lastUpdatedTimestamp": 1625476572000
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/guide/about.html",
      "relativePath": "guide/about.md",
      "key": "v-7cd147fa",
      "path": "/guide/about.html",
      "lastUpdated": "7/5/2021, 5:16:12 PM",
      "lastUpdatedTimestamp": 1625476572000
    },
    {
      "title": "我的2020总结",
      "frontmatter": {},
      "regularPath": "/guide/daily/2020.html",
      "relativePath": "guide/daily/2020.md",
      "key": "v-1b791ae2",
      "path": "/guide/daily/2020.html",
      "headers": [
        {
          "level": 2,
          "title": "疫情",
          "slug": "疫情"
        },
        {
          "level": 2,
          "title": "暑假",
          "slug": "暑假"
        },
        {
          "level": 2,
          "title": "大三上学期",
          "slug": "大三上学期"
        },
        {
          "level": 2,
          "title": "关于未来",
          "slug": "关于未来"
        },
        {
          "level": 2,
          "title": "HELLO 2021 !",
          "slug": "hello-2021"
        }
      ],
      "lastUpdated": "1/2/2021, 11:21:43 PM",
      "lastUpdatedTimestamp": 1609600903000
    },
    {
      "title": "生活日常",
      "frontmatter": {},
      "regularPath": "/guide/daily/",
      "relativePath": "guide/daily/README.md",
      "key": "v-7703af80",
      "path": "/guide/daily/",
      "lastUpdated": "11/23/2020, 10:42:28 PM",
      "lastUpdatedTimestamp": 1606142548000
    },
    {
      "title": "从零开始的博客开发(3)",
      "frontmatter": {},
      "regularPath": "/guide/BLOG/vueBlog3.html",
      "relativePath": "guide/BLOG/vueBlog3.md",
      "key": "v-5fece807",
      "path": "/guide/BLOG/vueBlog3.html",
      "headers": [
        {
          "level": 2,
          "title": "功能与问题",
          "slug": "功能与问题"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        },
        {
          "level": 3,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 3,
          "title": "返回顶部",
          "slug": "返回顶部"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "11/25/2020, 10:38:53 PM",
      "lastUpdatedTimestamp": 1606315133000
    },
    {
      "title": "从入职两个月开始",
      "frontmatter": {},
      "regularPath": "/guide/daily/2monthWork.html",
      "relativePath": "guide/daily/2monthWork.md",
      "key": "v-98864f6e",
      "path": "/guide/daily/2monthWork.html",
      "headers": [
        {
          "level": 2,
          "title": "毕业",
          "slug": "毕业"
        },
        {
          "level": 2,
          "title": "毕业后的日子",
          "slug": "毕业后的日子"
        },
        {
          "level": 2,
          "title": "来到北京",
          "slug": "来到北京"
        },
        {
          "level": 2,
          "title": "入职两个月的现在",
          "slug": "入职两个月的现在"
        }
      ],
      "lastUpdated": "8/28/2022, 8:03:43 PM",
      "lastUpdatedTimestamp": 1661688223000
    },
    {
      "title": "Today",
      "frontmatter": {},
      "regularPath": "/guide/daily/Today.html",
      "relativePath": "guide/daily/Today.md",
      "key": "v-294465ed",
      "path": "/guide/daily/Today.html",
      "lastUpdated": "11/5/2020, 10:39:34 PM",
      "lastUpdatedTimestamp": 1604587174000
    }
  ],
  "themeConfig": {
    "logo": "/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/guide/about",
        "target": ""
      },
      {
        "text": "博客",
        "link": "/guide/BLOG/",
        "target": ""
      },
      {
        "text": "算法",
        "link": "/guide/Algorithm/",
        "target": ""
      },
      {
        "text": "日常",
        "link": "/guide/daily/",
        "target": ""
      },
      {
        "text": "更多",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/DouMJun",
            "target": "_blank"
          },
          {
            "text": "bilibili",
            "link": "https://space.bilibili.com/8096424",
            "target": "_blank"
          }
        ]
      }
    ],
    "sidebar": {
      "/guide/BLOG/": [
        {
          "title": "博客",
          "children": [
            "watchMovie",
            "vueBlog2",
            "vueBlog3",
            "vueBlog4",
            "vuenexttick",
            "watch",
            "newVue",
            "nginxconf2",
            "presentational-container-pattern",
            "promise",
            "promise2",
            "autosidebar4",
            "closure",
            "copy",
            "debounce",
            "gitpageConfig",
            "mianshizongjie",
            "about;",
            "autosidebar3",
            "TailRecursion",
            "Watcher",
            "AutoSideBar",
            "AutoSideBar2",
            "BetterScroll",
            "Single"
          ]
        }
      ],
      "/guide/daily/": [
        {
          "title": "碎碎念",
          "children": [
            "2monthWork",
            "Today",
            "2020"
          ]
        }
      ],
      "/guide/Algorithm/": [
        {
          "title": "算法",
          "children": [
            "389.diff"
          ]
        }
      ],
      "/guide/": [
        {
          "title": "首页",
          "children": [
            "contact"
          ]
        }
      ]
    },
    "lastUpdated": "Last Updated"
  }
}